"""Adding link to user and admin

Revision ID: 3e7282bdcfd2
Revises: 7d1c042db7cc
Create Date: 2026-02-03 14:37:03.143069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7282bdcfd2'
down_revision: Union[str, Sequence[str], None] = '7d1c042db7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('connected_user_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('connected_admin_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'connected_admin_id')
    op.drop_column('users', 'connected_user_id')
    # ### end Alembic commands ###
