"""Adding admin columns

Revision ID: 7d1c042db7cc
Revises: d84f38ce430f
Create Date: 2026-02-03 12:33:36.948489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1c042db7cc'
down_revision: Union[str, Sequence[str], None] = 'd84f38ce430f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('admin_in_conversation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_in_conversation')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
